package:
  name: pymolnetenhancer
  version: 0.0.8

build:
  number: 3

requirements:
  run:
    - python
about:
  home: https://github.com/madeleineernst/pyMolNetEnhancer
  license: MIT
  license_file: LICENSE